name: Run tests on push

on: push

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: install pytest
              run: pip install pytest

            - name: Run specific file
              run: pytest.py
